### ISSUE TITLE
CSettingsManager: requested settings was not found

### ISSUE THREAD

**Issue by AchimTuran** [AlwinEsch/kodi#17]
With the current fork of AudioDSP there are some debug logs with not founded requested settings:

> DEBUG: CSettingsManager: requested setting (audiodsp.main.modetype) was not found.
DEBUG: CSettingsManager: requested setting (audiodsp.main.volume) was not found.
DEBUG: CSettingsManager: requested setting (audiodsp.main.menumaster) was not found.
DEBUG: CSettingsManager: requested setting (audiodsp.main.menupostproc) was not found.
DEBUG: CSettingsManager: requested setting (audiodsp.main.menuresample) was not found.
DEBUG: CSettingsManager: requested setting (audiodsp.main.menupreproc) was not found.
DEBUG: CSettingsManager: requested setting (audiodsp.main.menumisc) was not found.
DEBUG: CSettingsManager: requested setting (audiodsp.main.menuinfo) was not found.
DEBUG: CSettingsManager: requested setting (audiodsp.main.makedefault) was not found.
DEBUG: CSettingsManager: requested setting (audiodsp.proc.menu_0) was not found.
DEBUG: CSettingsManager: requested setting (audiodsp.info.inputchannels) was not found.
DEBUG: CSettingsManager: requested setting (audiodsp.info.inputchannelnames) was not found.
DEBUG: CSettingsManager: requested setting (audiodsp.info.inputsamplerate) was not found.
DEBUG: CSettingsManager: requested setting (audiodsp.info.outputchannels) was not found.
DEBUG: CSettingsManager: requested setting (audiodsp.info.outputchannelnames) was not found.
DEBUG: CSettingsManager: requested setting (audiodsp.info.outputsamplerate) was not found.
DEBUG: CSettingsManager: requested setting (audiodsp.info.cpuusage) was not found.
DEBUG: CSettingsManager: requested setting (audiodsp.info.modecpuusage_0) was not found.

**Comment by AlwinEsch** [comment]
Has fixed with https://github.com/AlwinEsch/kodi/commit/fd2e4528abc4314c0ca636202851c49e4ad3bfd9 dsp related faults with not present controls.

With "was not found" there is a bigger fault, which also related to all other dialogs and not related directly to dsp.

```
03:09:05 T:139987641243840   DEBUG: CSettingsManager: requested setting (audio.volume) was not found.
03:09:05 T:139987641243840   DEBUG: CSettingsManager: requested setting (audio.dsp) was not found.
03:09:05 T:139987641243840   DEBUG: CSettingsManager: requested setting (audio.stream) was not found.
03:09:05 T:139987641243840   DEBUG: CSettingsManager: requested setting (audio.digitalanalog) was not found.
03:09:05 T:139987641243840   DEBUG: CSettingsManager: requested setting (subtitles.enable) was not found.
03:09:05 T:139987641243840   DEBUG: CSettingsManager: requested setting (subtitles.delay) was not found.
03:09:05 T:139987641243840   DEBUG: CSettingsManager: requested setting (subtitles.stream) was not found.
03:09:05 T:139987641243840   DEBUG: CSettingsManager: requested setting (subtitles.browser) was not found.
03:09:05 T:139987641243840   DEBUG: CSettingsManager: requested setting (audio.makedefault) was not found.
```
```
03:09:54 T:139987641243840   DEBUG: CSettingsManager: requested setting (video.deinterlacemode) was not found.
03:09:54 T:139987641243840   DEBUG: CSettingsManager: requested setting (video.interlacemethod) was not found.
03:09:54 T:139987641243840   DEBUG: CSettingsManager: requested setting (video.scalingmethod) was not found.
03:09:54 T:139987641243840   DEBUG: CSettingsManager: requested setting (video.viewmode) was not found.
03:09:54 T:139987641243840   DEBUG: CSettingsManager: requested setting (video.zoom) was not found.
03:09:54 T:139987641243840   DEBUG: CSettingsManager: requested setting (video.verticalshift) was not found.
03:09:54 T:139987641243840   DEBUG: CSettingsManager: requested setting (video.pixelratio) was not found.
03:09:54 T:139987641243840   DEBUG: CSettingsManager: requested setting (video.postprocess) was not found.
03:09:54 T:139987641243840   DEBUG: CSettingsManager: requested setting (video.brightness) was not found.
03:09:54 T:139987641243840   DEBUG: CSettingsManager: requested setting (video.contrast) was not found.
03:09:54 T:139987641243840   DEBUG: CSettingsManager: requested setting (video.nonlinearstretch) was not found.
03:09:54 T:139987641243840   DEBUG: CSettingsManager: requested setting (video.stereoscopicmode) was not found.
03:09:54 T:139987641243840   DEBUG: CSettingsManager: requested setting (video.stereoscopicinvert) was not found.
03:09:54 T:139987641243840   DEBUG: CSettingsManager: requested setting (video.save) was not found.
03:09:54 T:139987641243840   DEBUG: CSettingsManager: requested setting (video.calibration) was not found.
```

**Comment by AchimTuran** [comment]
Can we close this?
