### ISSUE TITLE
Audio DSP Addons disabled when switching Kodi user profiles

### ISSUE THREAD

**Issue by SpaceAgeHero** [AlwinEsch/kodi#25]
When switching between mutliple Kodi user profiles there is a warning message and Audio DSP addons must be enabled manually again every time.

**Comment by AchimTuran** [comment]
Since AudioDSP is merged this is not the right place to post issues. Please use the AudioDSP subforum at forum.kodi.tv.

**Comment by SpaceAgeHero** [comment]
Okay thanks. I've done that. Is the feature request I've done for FreeSurround fine here on Github?

**Comment by AlwinEsch** [comment]
Thanks @SpaceAgeHero, I hope to look about it with you issue on free surround. To have the settings available for LFE is better if nothing else is present.
